// Generated by gencpp from file zxcar_3d_slam/GetObjectLocation.msg
// DO NOT EDIT!


#ifndef ZXCAR_3D_SLAM_MESSAGE_GETOBJECTLOCATION_H
#define ZXCAR_3D_SLAM_MESSAGE_GETOBJECTLOCATION_H

#include <ros/service_traits.h>


#include <zxcar_3d_slam/GetObjectLocationRequest.h>
#include <zxcar_3d_slam/GetObjectLocationResponse.h>


namespace zxcar_3d_slam
{

struct GetObjectLocation
{

typedef GetObjectLocationRequest Request;
typedef GetObjectLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectLocation
} // namespace zxcar_3d_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zxcar_3d_slam::GetObjectLocation > {
  static const char* value()
  {
    return "9d28df3ac07730491ae5838769a77b6a";
  }

  static const char* value(const ::zxcar_3d_slam::GetObjectLocation&) { return value(); }
};

template<>
struct DataType< ::zxcar_3d_slam::GetObjectLocation > {
  static const char* value()
  {
    return "zxcar_3d_slam/GetObjectLocation";
  }

  static const char* value(const ::zxcar_3d_slam::GetObjectLocation&) { return value(); }
};


// service_traits::MD5Sum< ::zxcar_3d_slam::GetObjectLocationRequest> should match
// service_traits::MD5Sum< ::zxcar_3d_slam::GetObjectLocation >
template<>
struct MD5Sum< ::zxcar_3d_slam::GetObjectLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zxcar_3d_slam::GetObjectLocation >::value();
  }
  static const char* value(const ::zxcar_3d_slam::GetObjectLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zxcar_3d_slam::GetObjectLocationRequest> should match
// service_traits::DataType< ::zxcar_3d_slam::GetObjectLocation >
template<>
struct DataType< ::zxcar_3d_slam::GetObjectLocationRequest>
{
  static const char* value()
  {
    return DataType< ::zxcar_3d_slam::GetObjectLocation >::value();
  }
  static const char* value(const ::zxcar_3d_slam::GetObjectLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zxcar_3d_slam::GetObjectLocationResponse> should match
// service_traits::MD5Sum< ::zxcar_3d_slam::GetObjectLocation >
template<>
struct MD5Sum< ::zxcar_3d_slam::GetObjectLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zxcar_3d_slam::GetObjectLocation >::value();
  }
  static const char* value(const ::zxcar_3d_slam::GetObjectLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zxcar_3d_slam::GetObjectLocationResponse> should match
// service_traits::DataType< ::zxcar_3d_slam::GetObjectLocation >
template<>
struct DataType< ::zxcar_3d_slam::GetObjectLocationResponse>
{
  static const char* value()
  {
    return DataType< ::zxcar_3d_slam::GetObjectLocation >::value();
  }
  static const char* value(const ::zxcar_3d_slam::GetObjectLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZXCAR_3D_SLAM_MESSAGE_GETOBJECTLOCATION_H
