// Generated by gencpp from file zxcar_3d_slam/GetObjectLocationResponse.msg
// DO NOT EDIT!


#ifndef ZXCAR_3D_SLAM_MESSAGE_GETOBJECTLOCATIONRESPONSE_H
#define ZXCAR_3D_SLAM_MESSAGE_GETOBJECTLOCATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace zxcar_3d_slam
{
template <class ContainerAllocator>
struct GetObjectLocationResponse_
{
  typedef GetObjectLocationResponse_<ContainerAllocator> Type;

  GetObjectLocationResponse_()
    : location()  {
    }
  GetObjectLocationResponse_(const ContainerAllocator& _alloc)
    : location(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetObjectLocationResponse_

typedef ::zxcar_3d_slam::GetObjectLocationResponse_<std::allocator<void> > GetObjectLocationResponse;

typedef boost::shared_ptr< ::zxcar_3d_slam::GetObjectLocationResponse > GetObjectLocationResponsePtr;
typedef boost::shared_ptr< ::zxcar_3d_slam::GetObjectLocationResponse const> GetObjectLocationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator1> & lhs, const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator1> & lhs, const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zxcar_3d_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34cf2a1ed77cb3529e2b342e07fb56b1";
  }

  static const char* value(const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34cf2a1ed77cb352ULL;
  static const uint64_t static_value2 = 0x9e2b342e07fb56b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zxcar_3d_slam/GetObjectLocationResponse";
  }

  static const char* value(const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray location\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetObjectLocationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zxcar_3d_slam::GetObjectLocationResponse_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZXCAR_3D_SLAM_MESSAGE_GETOBJECTLOCATIONRESPONSE_H
