(cl:defpackage zxcar_3d_slam-srv
  (:use )
  (:export
   "GETOBJECTLOCATION"
   "<GETOBJECTLOCATION-REQUEST>"
   "GETOBJECTLOCATION-REQUEST"
   "<GETOBJECTLOCATION-RESPONSE>"
   "GETOBJECTLOCATION-RESPONSE"
  ))

